spring:
  application:
    name: air-quality

  datasource:
    url: jdbc:postgresql://localhost:5432/airquality
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

external:
  city:
    url: https://api.europeancitiesdictionary.info